# https://goreleaser.com/customization/builds/
project_name: builder
builds:
  - id: builder
    env:
      # Force build to be all Go.
      - CGO_ENABLED=0
    flags:
      # Remove all file system paths from the executable.
      - -trimpath
    ldflags:
      # Disables DWARF debugging information.
      - -w
      # Disables symbol table information.
      - -s
      # Sets the value of the symbol.
      - -X github.com/ManInWeb3/flashbots-builder/config.Version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64
